name: .aifaps  # Environment name (you can change this if needed)
dependencies:
  - python=3.11  # Specify your Python version here
  - absl-py
  - aiohttp
  - aiosignal
  - alembic
  - asttokens
  - astunparse
  - async-timeout
  - attrs
  - backcall
  - bottle
  - cachetools
  - certifi
  - charset-normalizer
  - cmaes
  - cmake
  - colorama
  - colorlog
  - comm
  - contourpy
  - cycler
  - debugpy
  - decorator
  - et-xmlfile
  - executing
  - filelock
  - flatbuffers
  - fonttools
  - frozenlist
  - fsspec
  - gast
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - graphviz
  - greenlet
  - grpcio
  - gunicorn
  - h5py
  - idna
  - ipykernel
  - ipython
  - iterative-stratification
  - jedi
  - Jinja2
  - joblib
  - jupyter_client
  - jupyter_core
  - keras
  - keras-tuner
  - kiwisolver
  - kt-legacy
  - libclang
  - lightning-utilities
  - lit
  - Mako
  - Markdown
  - MarkupSafe
  - matplotlib
  - matplotlib-inline
  - ml-dtypes
  - mpmath
  - multidict
  - nest-asyncio
  - networkx
  - numpy
  - nvidia-cublas-cu11
  - nvidia-cublas-cu12
  - nvidia-cuda-cupti-cu11
  - nvidia-cuda-cupti-cu12
  - nvidia-cuda-nvrtc-cu11
  - nvidia-cuda-nvrtc-cu12
  - nvidia-cuda-runtime-cu11
  - nvidia-cuda-runtime-cu12
  - nvidia-cudnn-cu11
  - nvidia-cudnn-cu12
  - nvidia-cufft-cu11
  - nvidia-cufft-cu12
  - nvidia-curand-cu11
  - nvidia-curand-cu12
  - nvidia-cusolver-cu11
  - nvidia-cusolver-cu12
  - nvidia-cusparse-cu11
  - nvidia-cusparse-cu12
  - nvidia-nccl-cu11
  - nvidia-nccl-cu12
  - nvidia-nvjitlink-cu12
  - nvidia-nvtx-cu11
  - nvidia-nvtx-cu12
  - oauthlib
  - openpyxl
  - opt-einsum
  - optuna
  - optuna-dashboard
  - optuna-fast-fanova
  - packaging
  - pandas
  - parso
  - pexpect
  - pickleshare
  - Pillow
  - platformdirs
  - prompt-toolkit
  - protobuf
  - psutil
  - ptyprocess
  - pure-eval
  - pyasn1
  - pyasn1-modules
  - Pygments
  - pyparsing
  - python-dateutil
  - pytz
  - PyYAML
  - pyzmq
  - requests
  - requests-oauthlib
  - rsa
  - scikit-learn
  - scipy
  - seaborn
  - six
  - SQLAlchemy
  - stack-data
  - sympy
  - tensorboard
  - tensorboard-data-server
  - tensorflow
  - tensorflow-estimator
  - tensorflow-io-gcs-filesystem
  - termcolor
  - threadpoolctl
  - torch
  - torchmetrics
  - torchsummary
  - torchvision
  - torchviz
  - tornado
  - tqdm
  - traitlets
  - triton
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - Werkzeug
  - wrapt
  - yarl
